# Generated by Django 4.0.5 on 2022-08-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='topic',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='topic',
            new_name='category',
        ),
    ]
